// <auto-generated>
//     Generated by Tools/build_gaze_patterns.py from the ICMI paper's raw
//     prototype archives. Do not edit by hand - regenerate instead.
// </auto-generated>

using System.Collections.Generic;

namespace GazeControl.Gaze.Policy
{
    /// <summary>The fifteen pre-turn prototypes printed in the paper, by figure.</summary>
    public enum PreTurnPattern
    {
        /// <summary>p1_ks20_5, class Interruption.</summary>
        Fig6a,
        /// <summary>p1_ks20_6, class Interruption.</summary>
        Fig6b,
        /// <summary>p2_ks20_0, class Overlapping.</summary>
        Fig6c,
        /// <summary>p3_ks20_3, class TurnTaking.</summary>
        Fig6d,
        /// <summary>p3_ks20_14, class TurnTaking.</summary>
        Fig6e,
        /// <summary>p1_ks30_18, class Interruption.</summary>
        Fig7a,
        /// <summary>p2_ks30_9, class Overlapping.</summary>
        Fig7b,
        /// <summary>p2_ks30_16, class Overlapping.</summary>
        Fig7c,
        /// <summary>p3_ks30_2, class TurnTaking.</summary>
        Fig7d,
        /// <summary>p3_ks30_17, class TurnTaking.</summary>
        Fig7e,
        /// <summary>p1_ks40_4, class Interruption.</summary>
        Fig8a,
        /// <summary>p1_ks40_12, class Interruption.</summary>
        Fig8b,
        /// <summary>p2_ks40_9, class Overlapping.</summary>
        Fig8c,
        /// <summary>p3_ks40_4, class TurnTaking.</summary>
        Fig8d,
        /// <summary>p3_ks40_19, class TurnTaking.</summary>
        Fig8e,
    }

    /// <summary>
    /// Pre-turn gaze prototypes transcribed from the ICMI paper's raw prototype
    /// data (Figures 6-8; filter sizes 20, 30 and 40). Each is a one-second
    /// window at 60 fps ending at an end-of-turn event, with one track per
    /// conversational role.
    /// </summary>
    public static class GazePatterns
    {
        const float Frame = 1f / 60f;

        /// <summary>
        /// Fig6a (p1_ks20_5, interruption): the next speaker turns to the current speaker, the current speaker turns to the listener, and the listener keeps watching the current speaker (paper Sec. 5).
        /// Filter size 20; the rank-0 matched subsequence starts at
        /// window frame 19 of 60.
        /// </summary>
        public static readonly GazePattern Fig6a = new()
        {
            Name = "Fig6a p1_ks20_5 (interruption)",
            PrototypeId = "p1_ks20_5",
            EotType = EotType.Interruption,
            WindowOffsetSeconds = 19 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (7 * Frame, GazeRole.None),
                (7 * Frame, GazeRole.Listener),
                (3 * Frame, GazeRole.None),
                (3 * Frame, GazeRole.Listener),
            },
            NextSpeakerTrack = new[]
            {
                (13 * Frame, GazeRole.None),
                (7 * Frame, GazeRole.CurrentSpeaker),
            },
            ListenerTrack = new[]
            {
                (20 * Frame, GazeRole.CurrentSpeaker),
            },
        };

        /// <summary>
        /// Fig6b (p1_ks20_6, interruption): current speaker: listener -> aversion -> listener; next speaker: aversion -> currentspeaker; listener: aversion.
        /// Filter size 20; the rank-0 matched subsequence starts at
        /// window frame 30 of 60.
        /// </summary>
        public static readonly GazePattern Fig6b = new()
        {
            Name = "Fig6b p1_ks20_6 (interruption)",
            PrototypeId = "p1_ks20_6",
            EotType = EotType.Interruption,
            WindowOffsetSeconds = 30 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (7 * Frame, GazeRole.Listener),
                (2 * Frame, GazeRole.None),
                (11 * Frame, GazeRole.Listener),
            },
            NextSpeakerTrack = new[]
            {
                (15 * Frame, GazeRole.None),
                (5 * Frame, GazeRole.CurrentSpeaker),
            },
            ListenerTrack = new[]
            {
                (20 * Frame, GazeRole.None),
            },
        };

        /// <summary>
        /// Fig6c (p2_ks20_0, overlapping): current speaker: aversion -> nextspeaker; next speaker: aversion; listener: nextspeaker -> aversion.
        /// Filter size 20; the rank-0 matched subsequence starts at
        /// window frame 26 of 60.
        /// </summary>
        public static readonly GazePattern Fig6c = new()
        {
            Name = "Fig6c p2_ks20_0 (overlapping)",
            PrototypeId = "p2_ks20_0",
            EotType = EotType.Overlapping,
            WindowOffsetSeconds = 26 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (7 * Frame, GazeRole.None),
                (13 * Frame, GazeRole.NextSpeaker),
            },
            NextSpeakerTrack = new[]
            {
                (20 * Frame, GazeRole.None),
            },
            ListenerTrack = new[]
            {
                (1 * Frame, GazeRole.NextSpeaker),
                (19 * Frame, GazeRole.None),
            },
        };

        /// <summary>
        /// Fig6d (p3_ks20_3, turn-taking): current speaker: aversion -> nextspeaker -> aversion; next speaker: aversion -> currentspeaker -> aversion -> currentspeaker -> aversion; listener: currentspeaker.
        /// Filter size 20; the rank-0 matched subsequence starts at
        /// window frame 21 of 60.
        /// </summary>
        public static readonly GazePattern Fig6d = new()
        {
            Name = "Fig6d p3_ks20_3 (turn-taking)",
            PrototypeId = "p3_ks20_3",
            EotType = EotType.TurnTaking,
            WindowOffsetSeconds = 21 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (4 * Frame, GazeRole.None),
                (2 * Frame, GazeRole.NextSpeaker),
                (14 * Frame, GazeRole.None),
            },
            NextSpeakerTrack = new[]
            {
                (12 * Frame, GazeRole.None),
                (3 * Frame, GazeRole.CurrentSpeaker),
                (2 * Frame, GazeRole.None),
                (1 * Frame, GazeRole.CurrentSpeaker),
                (2 * Frame, GazeRole.None),
            },
            ListenerTrack = new[]
            {
                (20 * Frame, GazeRole.CurrentSpeaker),
            },
        };

        /// <summary>
        /// Fig6e (p3_ks20_14, turn-taking): current speaker: nextspeaker -> aversion -> nextspeaker -> aversion -> nextspeaker; next speaker: currentspeaker -> aversion -> currentspeaker -> aversion; listener: currentspeaker.
        /// Filter size 20; the rank-0 matched subsequence starts at
        /// window frame 38 of 60.
        /// </summary>
        public static readonly GazePattern Fig6e = new()
        {
            Name = "Fig6e p3_ks20_14 (turn-taking)",
            PrototypeId = "p3_ks20_14",
            EotType = EotType.TurnTaking,
            WindowOffsetSeconds = 38 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (9 * Frame, GazeRole.NextSpeaker),
                (4 * Frame, GazeRole.None),
                (4 * Frame, GazeRole.NextSpeaker),
                (2 * Frame, GazeRole.None),
                (1 * Frame, GazeRole.NextSpeaker),
            },
            NextSpeakerTrack = new[]
            {
                (9 * Frame, GazeRole.CurrentSpeaker),
                (5 * Frame, GazeRole.None),
                (2 * Frame, GazeRole.CurrentSpeaker),
                (4 * Frame, GazeRole.None),
            },
            ListenerTrack = new[]
            {
                (20 * Frame, GazeRole.CurrentSpeaker),
            },
        };

        /// <summary>
        /// Fig7a (p1_ks30_18, interruption): the listener averts gaze while the next speaker turns to the current speaker, before an interruption (paper Sec. 5).
        /// Filter size 30; the rank-0 matched subsequence starts at
        /// window frame 26 of 60.
        /// </summary>
        public static readonly GazePattern Fig7a = new()
        {
            Name = "Fig7a p1_ks30_18 (interruption)",
            PrototypeId = "p1_ks30_18",
            EotType = EotType.Interruption,
            WindowOffsetSeconds = 26 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (30 * Frame, GazeRole.None),
            },
            NextSpeakerTrack = new[]
            {
                (28 * Frame, GazeRole.None),
                (2 * Frame, GazeRole.CurrentSpeaker),
            },
            ListenerTrack = new[]
            {
                (8 * Frame, GazeRole.CurrentSpeaker),
                (22 * Frame, GazeRole.None),
            },
        };

        /// <summary>
        /// Fig7b (p2_ks30_9, overlapping): current speaker: nextspeaker -> aversion; next speaker: currentspeaker -> aversion -> currentspeaker -> aversion; listener: aversion.
        /// Filter size 30; the rank-0 matched subsequence starts at
        /// window frame 0 of 60.
        /// </summary>
        public static readonly GazePattern Fig7b = new()
        {
            Name = "Fig7b p2_ks30_9 (overlapping)",
            PrototypeId = "p2_ks30_9",
            EotType = EotType.Overlapping,
            WindowOffsetSeconds = 0 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (26 * Frame, GazeRole.NextSpeaker),
                (4 * Frame, GazeRole.None),
            },
            NextSpeakerTrack = new[]
            {
                (1 * Frame, GazeRole.CurrentSpeaker),
                (20 * Frame, GazeRole.None),
                (2 * Frame, GazeRole.CurrentSpeaker),
                (7 * Frame, GazeRole.None),
            },
            ListenerTrack = new[]
            {
                (30 * Frame, GazeRole.None),
            },
        };

        /// <summary>
        /// Fig7c (p2_ks30_16, overlapping): current speaker: nextspeaker -> aversion; next speaker: listener -> aversion -> currentspeaker -> aversion -> listener -> aversion -> currentspeaker; listener: aversion.
        /// Filter size 30; the rank-0 matched subsequence starts at
        /// window frame 10 of 60.
        /// </summary>
        public static readonly GazePattern Fig7c = new()
        {
            Name = "Fig7c p2_ks30_16 (overlapping)",
            PrototypeId = "p2_ks30_16",
            EotType = EotType.Overlapping,
            WindowOffsetSeconds = 10 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (5 * Frame, GazeRole.NextSpeaker),
                (25 * Frame, GazeRole.None),
            },
            NextSpeakerTrack = new[]
            {
                (11 * Frame, GazeRole.Listener),
                (1 * Frame, GazeRole.None),
                (7 * Frame, GazeRole.CurrentSpeaker),
                (6 * Frame, GazeRole.None),
                (2 * Frame, GazeRole.Listener),
                (1 * Frame, GazeRole.None),
                (2 * Frame, GazeRole.CurrentSpeaker),
            },
            ListenerTrack = new[]
            {
                (30 * Frame, GazeRole.None),
            },
        };

        /// <summary>
        /// Fig7d (p3_ks30_2, turn-taking): current speaker: nextspeaker; next speaker: aversion -> currentspeaker -> aversion -> currentspeaker -> aversion -> currentspeaker -> aversion; listener: nextspeaker -> aversion -> nextspeaker.
        /// Filter size 30; the rank-0 matched subsequence starts at
        /// window frame 5 of 60.
        /// </summary>
        public static readonly GazePattern Fig7d = new()
        {
            Name = "Fig7d p3_ks30_2 (turn-taking)",
            PrototypeId = "p3_ks30_2",
            EotType = EotType.TurnTaking,
            WindowOffsetSeconds = 5 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (30 * Frame, GazeRole.NextSpeaker),
            },
            NextSpeakerTrack = new[]
            {
                (6 * Frame, GazeRole.None),
                (3 * Frame, GazeRole.CurrentSpeaker),
                (1 * Frame, GazeRole.None),
                (1 * Frame, GazeRole.CurrentSpeaker),
                (5 * Frame, GazeRole.None),
                (11 * Frame, GazeRole.CurrentSpeaker),
                (3 * Frame, GazeRole.None),
            },
            ListenerTrack = new[]
            {
                (13 * Frame, GazeRole.NextSpeaker),
                (16 * Frame, GazeRole.None),
                (1 * Frame, GazeRole.NextSpeaker),
            },
        };

        /// <summary>
        /// Fig7e (p3_ks30_17, turn-taking): current speaker: nextspeaker -> aversion -> nextspeaker; next speaker: currentspeaker -> aversion; listener: aversion -> currentspeaker -> aversion.
        /// Filter size 30; the rank-0 matched subsequence starts at
        /// window frame 29 of 60.
        /// </summary>
        public static readonly GazePattern Fig7e = new()
        {
            Name = "Fig7e p3_ks30_17 (turn-taking)",
            PrototypeId = "p3_ks30_17",
            EotType = EotType.TurnTaking,
            WindowOffsetSeconds = 29 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (5 * Frame, GazeRole.NextSpeaker),
                (17 * Frame, GazeRole.None),
                (8 * Frame, GazeRole.NextSpeaker),
            },
            NextSpeakerTrack = new[]
            {
                (20 * Frame, GazeRole.CurrentSpeaker),
                (10 * Frame, GazeRole.None),
            },
            ListenerTrack = new[]
            {
                (18 * Frame, GazeRole.None),
                (4 * Frame, GazeRole.CurrentSpeaker),
                (8 * Frame, GazeRole.None),
            },
        };

        /// <summary>
        /// Fig8a (p1_ks40_4, interruption): current speaker: aversion; next speaker: aversion -> currentspeaker; listener: currentspeaker.
        /// Filter size 40; the rank-0 matched subsequence starts at
        /// window frame 20 of 60.
        /// </summary>
        public static readonly GazePattern Fig8a = new()
        {
            Name = "Fig8a p1_ks40_4 (interruption)",
            PrototypeId = "p1_ks40_4",
            EotType = EotType.Interruption,
            WindowOffsetSeconds = 20 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (40 * Frame, GazeRole.None),
            },
            NextSpeakerTrack = new[]
            {
                (26 * Frame, GazeRole.None),
                (14 * Frame, GazeRole.CurrentSpeaker),
            },
            ListenerTrack = new[]
            {
                (40 * Frame, GazeRole.CurrentSpeaker),
            },
        };

        /// <summary>
        /// Fig8b (p1_ks40_12, interruption): current speaker: nextspeaker -> aversion -> nextspeaker; next speaker: aversion -> currentspeaker; listener: currentspeaker -> aversion -> currentspeaker -> aversion -> currentspeaker -> aversion.
        /// Filter size 40; the rank-0 matched subsequence starts at
        /// window frame 2 of 60.
        /// </summary>
        public static readonly GazePattern Fig8b = new()
        {
            Name = "Fig8b p1_ks40_12 (interruption)",
            PrototypeId = "p1_ks40_12",
            EotType = EotType.Interruption,
            WindowOffsetSeconds = 2 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (13 * Frame, GazeRole.NextSpeaker),
                (15 * Frame, GazeRole.None),
                (12 * Frame, GazeRole.NextSpeaker),
            },
            NextSpeakerTrack = new[]
            {
                (34 * Frame, GazeRole.None),
                (6 * Frame, GazeRole.CurrentSpeaker),
            },
            ListenerTrack = new[]
            {
                (3 * Frame, GazeRole.CurrentSpeaker),
                (6 * Frame, GazeRole.None),
                (2 * Frame, GazeRole.CurrentSpeaker),
                (6 * Frame, GazeRole.None),
                (4 * Frame, GazeRole.CurrentSpeaker),
                (19 * Frame, GazeRole.None),
            },
        };

        /// <summary>
        /// Fig8c (p2_ks40_9, overlapping): current speaker: listener -> aversion -> nextspeaker -> aversion; next speaker: currentspeaker -> aversion; listener: aversion -> currentspeaker -> aversion -> currentspeaker -> aversion.
        /// Filter size 40; the rank-0 matched subsequence starts at
        /// window frame 14 of 60.
        /// </summary>
        public static readonly GazePattern Fig8c = new()
        {
            Name = "Fig8c p2_ks40_9 (overlapping)",
            PrototypeId = "p2_ks40_9",
            EotType = EotType.Overlapping,
            WindowOffsetSeconds = 14 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (19 * Frame, GazeRole.Listener),
                (8 * Frame, GazeRole.None),
                (3 * Frame, GazeRole.NextSpeaker),
                (10 * Frame, GazeRole.None),
            },
            NextSpeakerTrack = new[]
            {
                (36 * Frame, GazeRole.CurrentSpeaker),
                (4 * Frame, GazeRole.None),
            },
            ListenerTrack = new[]
            {
                (12 * Frame, GazeRole.None),
                (1 * Frame, GazeRole.CurrentSpeaker),
                (1 * Frame, GazeRole.None),
                (1 * Frame, GazeRole.CurrentSpeaker),
                (25 * Frame, GazeRole.None),
            },
        };

        /// <summary>
        /// Fig8d (p3_ks40_4, turn-taking): the current speaker glances at the next speaker twice before yielding the turn (paper Sec. 5).
        /// Filter size 40; the rank-0 matched subsequence starts at
        /// window frame 4 of 60.
        /// </summary>
        public static readonly GazePattern Fig8d = new()
        {
            Name = "Fig8d p3_ks40_4 (turn-taking)",
            PrototypeId = "p3_ks40_4",
            EotType = EotType.TurnTaking,
            WindowOffsetSeconds = 4 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (1 * Frame, GazeRole.None),
                (2 * Frame, GazeRole.NextSpeaker),
                (1 * Frame, GazeRole.None),
                (3 * Frame, GazeRole.NextSpeaker),
                (33 * Frame, GazeRole.None),
            },
            NextSpeakerTrack = new[]
            {
                (40 * Frame, GazeRole.None),
            },
            ListenerTrack = new[]
            {
                (4 * Frame, GazeRole.None),
                (1 * Frame, GazeRole.CurrentSpeaker),
                (35 * Frame, GazeRole.None),
            },
        };

        /// <summary>
        /// Fig8e (p3_ks40_19, turn-taking): current speaker: nextspeaker -> aversion; next speaker: currentspeaker; listener: currentspeaker.
        /// Filter size 40; the rank-0 matched subsequence starts at
        /// window frame 0 of 60.
        /// </summary>
        public static readonly GazePattern Fig8e = new()
        {
            Name = "Fig8e p3_ks40_19 (turn-taking)",
            PrototypeId = "p3_ks40_19",
            EotType = EotType.TurnTaking,
            WindowOffsetSeconds = 0 * Frame,
            CurrentSpeakerTrack = new[]
            {
                (13 * Frame, GazeRole.NextSpeaker),
                (27 * Frame, GazeRole.None),
            },
            NextSpeakerTrack = new[]
            {
                (40 * Frame, GazeRole.CurrentSpeaker),
            },
            ListenerTrack = new[]
            {
                (40 * Frame, GazeRole.CurrentSpeaker),
            },
        };

        /// <summary>Every prototype the paper prints, in figure order.</summary>
        public static readonly IReadOnlyList<GazePattern> All = new[]
        {
            Fig6a,
            Fig6b,
            Fig6c,
            Fig6d,
            Fig6e,
            Fig7a,
            Fig7b,
            Fig7c,
            Fig7d,
            Fig7e,
            Fig8a,
            Fig8b,
            Fig8c,
            Fig8d,
            Fig8e,
        };

        /// <summary>The prototypes the paper labels interruption.</summary>
        public static readonly IReadOnlyList<GazePattern> InterruptionPool = new[]
        {
            Fig6a,
            Fig6b,
            Fig7a,
            Fig8a,
            Fig8b,
        };

        /// <summary>The prototypes the paper labels overlapping.</summary>
        public static readonly IReadOnlyList<GazePattern> OverlappingPool = new[]
        {
            Fig6c,
            Fig7b,
            Fig7c,
            Fig8c,
        };

        /// <summary>The prototypes the paper labels turntaking.</summary>
        public static readonly IReadOnlyList<GazePattern> TurnTakingPool = new[]
        {
            Fig6d,
            Fig6e,
            Fig7d,
            Fig7e,
            Fig8d,
            Fig8e,
        };

        /// <summary>The named prototype.</summary>
        public static GazePattern Of(PreTurnPattern pattern) => All[(int)pattern];

        /// <summary>
        /// The prototypes measured on events of this class. The proposed
        /// condition draws from the pool matching each event's own type, so an
        /// interruption never gets a turn-taking prototype played over it.
        /// </summary>
        public static IReadOnlyList<GazePattern> PoolFor(EotType eotType) => eotType switch
        {
            EotType.Interruption => InterruptionPool,
            EotType.Overlapping => OverlappingPool,
            _ => TurnTakingPool,
        };
    }
}
